/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package teclado;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.util.Date;
import java.util.Random;
import javax.swing.JButton;
import javax.swing.JOptionPane;


public class Tela extends javax.swing.JFrame {
    
    String frases[] = new String[5];
    int backspace = 0;
    
    //variavel que armazena a posição da frase no vetor frases
        int posicao;
    
    public Tela() {
        
        initComponents();
        jTextArea1.setEnabled(false);
        jButton2.setEnabled(false);
    
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_frase = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        jToggleButton4 = new javax.swing.JToggleButton();
        jToggleButton5 = new javax.swing.JToggleButton();
        jToggleButton6 = new javax.swing.JToggleButton();
        jToggleButton7 = new javax.swing.JToggleButton();
        jToggleButton8 = new javax.swing.JToggleButton();
        jToggleButton9 = new javax.swing.JToggleButton();
        jToggleButton10 = new javax.swing.JToggleButton();
        jToggleButton11 = new javax.swing.JToggleButton();
        jToggleButton12 = new javax.swing.JToggleButton();
        jToggleButton13 = new javax.swing.JToggleButton();
        jToggleButton14 = new javax.swing.JToggleButton();
        jToggleButton15 = new javax.swing.JToggleButton();
        jToggleButton16 = new javax.swing.JToggleButton();
        jToggleButton17 = new javax.swing.JToggleButton();
        jToggleButton18 = new javax.swing.JToggleButton();
        jToggleButton19 = new javax.swing.JToggleButton();
        jToggleButton20 = new javax.swing.JToggleButton();
        jToggleButton21 = new javax.swing.JToggleButton();
        jToggleButton22 = new javax.swing.JToggleButton();
        jToggleButton23 = new javax.swing.JToggleButton();
        jToggleButton24 = new javax.swing.JToggleButton();
        jToggleButton25 = new javax.swing.JToggleButton();
        jToggleButton26 = new javax.swing.JToggleButton();
        jToggleButton27 = new javax.swing.JToggleButton();
        jToggleButton28 = new javax.swing.JToggleButton();
        jToggleButton29 = new javax.swing.JToggleButton();
        jToggleButton30 = new javax.swing.JToggleButton();
        jToggleButton31 = new javax.swing.JToggleButton();
        jToggleButton32 = new javax.swing.JToggleButton();
        jToggleButton33 = new javax.swing.JToggleButton();
        jToggleButton34 = new javax.swing.JToggleButton();
        jToggleButton35 = new javax.swing.JToggleButton();
        jToggleButton36 = new javax.swing.JToggleButton();
        jToggleButton37 = new javax.swing.JToggleButton();
        jToggleButton38 = new javax.swing.JToggleButton();
        jToggleButton39 = new javax.swing.JToggleButton();
        jToggleButton40 = new javax.swing.JToggleButton();
        jToggleButton41 = new javax.swing.JToggleButton();
        jToggleButton42 = new javax.swing.JToggleButton();
        jToggleButton43 = new javax.swing.JToggleButton();
        jToggleButton44 = new javax.swing.JToggleButton();
        jToggleButton45 = new javax.swing.JToggleButton();
        jToggleButton46 = new javax.swing.JToggleButton();
        jToggleButton47 = new javax.swing.JToggleButton();
        jToggleButton48 = new javax.swing.JToggleButton();
        jToggleButton49 = new javax.swing.JToggleButton();
        jToggleButton50 = new javax.swing.JToggleButton();
        jToggleButton51 = new javax.swing.JToggleButton();
        jToggleButton52 = new javax.swing.JToggleButton();
        jToggleButton53 = new javax.swing.JToggleButton();
        lbl_hora = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jToggleButton54 = new javax.swing.JToggleButton();
        jToggleButton55 = new javax.swing.JToggleButton();
        jToggleButton56 = new javax.swing.JToggleButton();
        jToggleButton57 = new javax.swing.JToggleButton();
        jToggleButton58 = new javax.swing.JToggleButton();
        jToggleButton59 = new javax.swing.JToggleButton();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lbl_erros = new javax.swing.JLabel();
        lbl_erros1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 51, 51));
        setPreferredSize(new java.awt.Dimension(803, 586));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        lbl_frase.setBackground(new java.awt.Color(255, 255, 255));
        lbl_frase.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        lbl_frase.setForeground(new java.awt.Color(0, 153, 153));
        lbl_frase.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lbl_frase);
        lbl_frase.setBounds(40, 50, 710, 40);

        jToggleButton1.setBackground(new java.awt.Color(255, 255, 255));
        jToggleButton1.setText("'");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton1);
        jToggleButton1.setBounds(8, 206, 39, 38);

        jToggleButton2.setBackground(new java.awt.Color(255, 255, 255));
        jToggleButton2.setText("1");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });
        jToggleButton2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jToggleButton2KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jToggleButton2KeyReleased(evt);
            }
        });
        jPanel1.add(jToggleButton2);
        jToggleButton2.setBounds(53, 206, 39, 38);

        jToggleButton3.setBackground(new java.awt.Color(255, 255, 255));
        jToggleButton3.setText("2");
        jToggleButton3.setMaximumSize(new java.awt.Dimension(39, 39));
        jPanel1.add(jToggleButton3);
        jToggleButton3.setBounds(98, 206, 39, 38);

        jToggleButton4.setBackground(new java.awt.Color(255, 255, 255));
        jToggleButton4.setText("3");
        jPanel1.add(jToggleButton4);
        jToggleButton4.setBounds(143, 206, 39, 38);

        jToggleButton5.setBackground(new java.awt.Color(255, 255, 255));
        jToggleButton5.setText("4");
        jPanel1.add(jToggleButton5);
        jToggleButton5.setBounds(188, 206, 39, 38);

        jToggleButton6.setBackground(new java.awt.Color(255, 255, 255));
        jToggleButton6.setText("5");
        jToggleButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton6);
        jToggleButton6.setBounds(233, 206, 39, 38);

        jToggleButton7.setBackground(new java.awt.Color(255, 255, 255));
        jToggleButton7.setText("6");
        jPanel1.add(jToggleButton7);
        jToggleButton7.setBounds(278, 206, 39, 38);

        jToggleButton8.setBackground(new java.awt.Color(255, 255, 255));
        jToggleButton8.setText("7");
        jPanel1.add(jToggleButton8);
        jToggleButton8.setBounds(323, 206, 39, 38);

        jToggleButton9.setBackground(new java.awt.Color(255, 255, 255));
        jToggleButton9.setText("8");
        jPanel1.add(jToggleButton9);
        jToggleButton9.setBounds(368, 206, 39, 38);

        jToggleButton10.setBackground(new java.awt.Color(255, 255, 255));
        jToggleButton10.setText("9");
        jToggleButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton10ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton10);
        jToggleButton10.setBounds(413, 206, 39, 38);

        jToggleButton11.setBackground(new java.awt.Color(255, 255, 255));
        jToggleButton11.setText("0");
        jPanel1.add(jToggleButton11);
        jToggleButton11.setBounds(458, 206, 39, 38);

        jToggleButton12.setBackground(new java.awt.Color(255, 255, 255));
        jToggleButton12.setText("-");
        jPanel1.add(jToggleButton12);
        jToggleButton12.setBounds(503, 206, 39, 38);

        jToggleButton13.setBackground(new java.awt.Color(255, 255, 255));
        jToggleButton13.setText("=");
        jToggleButton13.setMaximumSize(new java.awt.Dimension(39, 39));
        jToggleButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton13ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton13);
        jToggleButton13.setBounds(548, 206, 41, 38);

        jToggleButton14.setBackground(new java.awt.Color(255, 255, 255));
        jToggleButton14.setText("TAB");
        jToggleButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton14ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton14);
        jToggleButton14.setBounds(8, 251, 63, 38);

        jToggleButton15.setBackground(new java.awt.Color(255, 255, 255));
        jToggleButton15.setText("Q");
        jPanel1.add(jToggleButton15);
        jToggleButton15.setBounds(77, 251, 41, 38);

        jToggleButton16.setBackground(new java.awt.Color(255, 255, 255));
        jToggleButton16.setText("W");
        jPanel1.add(jToggleButton16);
        jToggleButton16.setBounds(122, 251, 43, 38);

        jToggleButton17.setBackground(new java.awt.Color(255, 255, 255));
        jToggleButton17.setText("E");
        jToggleButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton17ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton17);
        jToggleButton17.setBounds(171, 251, 39, 38);

        jToggleButton18.setBackground(new java.awt.Color(255, 255, 255));
        jToggleButton18.setText("R");
        jPanel1.add(jToggleButton18);
        jToggleButton18.setBounds(216, 251, 39, 38);

        jToggleButton19.setBackground(new java.awt.Color(255, 255, 255));
        jToggleButton19.setText("T");
        jPanel1.add(jToggleButton19);
        jToggleButton19.setBounds(261, 251, 39, 38);

        jToggleButton20.setBackground(new java.awt.Color(255, 255, 255));
        jToggleButton20.setText("Y");
        jPanel1.add(jToggleButton20);
        jToggleButton20.setBounds(306, 251, 39, 38);

        jToggleButton21.setBackground(new java.awt.Color(255, 255, 255));
        jToggleButton21.setText("U");
        jPanel1.add(jToggleButton21);
        jToggleButton21.setBounds(351, 251, 39, 38);

        jToggleButton22.setBackground(new java.awt.Color(255, 255, 255));
        jToggleButton22.setText("I");
        jPanel1.add(jToggleButton22);
        jToggleButton22.setBounds(396, 251, 39, 38);

        jToggleButton23.setBackground(new java.awt.Color(255, 255, 255));
        jToggleButton23.setText("O");
        jToggleButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton23ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton23);
        jToggleButton23.setBounds(441, 251, 43, 38);

        jToggleButton24.setBackground(new java.awt.Color(255, 255, 255));
        jToggleButton24.setText("P");
        jPanel1.add(jToggleButton24);
        jToggleButton24.setBounds(490, 251, 39, 38);

        jToggleButton25.setBackground(new java.awt.Color(255, 255, 255));
        jToggleButton25.setText("´");
        jPanel1.add(jToggleButton25);
        jToggleButton25.setBounds(535, 251, 39, 38);

        jToggleButton26.setBackground(new java.awt.Color(255, 255, 255));
        jToggleButton26.setText("[");
        jPanel1.add(jToggleButton26);
        jToggleButton26.setBounds(580, 251, 39, 38);

        jToggleButton27.setBackground(new java.awt.Color(255, 255, 255));
        jToggleButton27.setText("Caps Lock");
        jPanel1.add(jToggleButton27);
        jToggleButton27.setBounds(8, 298, 81, 36);

        jToggleButton28.setBackground(new java.awt.Color(255, 255, 255));
        jToggleButton28.setText("A");
        jToggleButton28.setPreferredSize(new java.awt.Dimension(43, 23));
        jPanel1.add(jToggleButton28);
        jToggleButton28.setBounds(95, 297, 43, 38);

        jToggleButton29.setBackground(new java.awt.Color(255, 255, 255));
        jToggleButton29.setText("S");
        jPanel1.add(jToggleButton29);
        jToggleButton29.setBounds(144, 297, 39, 38);

        jToggleButton30.setBackground(new java.awt.Color(255, 255, 255));
        jToggleButton30.setText("D");
        jToggleButton30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton30ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton30);
        jToggleButton30.setBounds(189, 297, 39, 38);

        jToggleButton31.setBackground(new java.awt.Color(255, 255, 255));
        jToggleButton31.setText("F");
        jPanel1.add(jToggleButton31);
        jToggleButton31.setBounds(234, 298, 39, 37);

        jToggleButton32.setBackground(new java.awt.Color(255, 255, 255));
        jToggleButton32.setText("G");
        jToggleButton32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton32ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton32);
        jToggleButton32.setBounds(279, 297, 39, 38);

        jToggleButton33.setBackground(new java.awt.Color(255, 255, 255));
        jToggleButton33.setText("H");
        jToggleButton33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton33ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton33);
        jToggleButton33.setBounds(322, 298, 39, 38);

        jToggleButton34.setBackground(new java.awt.Color(255, 255, 255));
        jToggleButton34.setText("J");
        jPanel1.add(jToggleButton34);
        jToggleButton34.setBounds(367, 298, 39, 38);

        jToggleButton35.setBackground(new java.awt.Color(255, 255, 255));
        jToggleButton35.setText("K");
        jPanel1.add(jToggleButton35);
        jToggleButton35.setBounds(412, 298, 39, 38);

        jToggleButton36.setBackground(new java.awt.Color(255, 255, 255));
        jToggleButton36.setText("L");
        jPanel1.add(jToggleButton36);
        jToggleButton36.setBounds(457, 297, 39, 38);

        jToggleButton37.setBackground(new java.awt.Color(255, 255, 255));
        jToggleButton37.setText("Ç");
        jPanel1.add(jToggleButton37);
        jToggleButton37.setBounds(502, 297, 39, 38);

        jToggleButton38.setBackground(new java.awt.Color(255, 255, 255));
        jToggleButton38.setText("~");
        jPanel1.add(jToggleButton38);
        jToggleButton38.setBounds(547, 297, 41, 38);

        jToggleButton39.setBackground(new java.awt.Color(255, 255, 255));
        jToggleButton39.setText("]");
        jPanel1.add(jToggleButton39);
        jToggleButton39.setBounds(594, 297, 40, 38);

        jToggleButton40.setBackground(new java.awt.Color(255, 255, 255));
        jToggleButton40.setText("SHIFT");
        jPanel1.add(jToggleButton40);
        jToggleButton40.setBounds(8, 341, 61, 40);

        jToggleButton41.setBackground(new java.awt.Color(255, 255, 255));
        jToggleButton41.setText("/");
        jPanel1.add(jToggleButton41);
        jToggleButton41.setBounds(433, 341, 39, 40);

        jToggleButton42.setBackground(new java.awt.Color(255, 255, 255));
        jToggleButton42.setText(",");
        jPanel1.add(jToggleButton42);
        jToggleButton42.setBounds(478, 341, 39, 40);

        jToggleButton43.setBackground(new java.awt.Color(255, 255, 255));
        jToggleButton43.setText(".");
        jPanel1.add(jToggleButton43);
        jToggleButton43.setBounds(523, 341, 39, 41);

        jToggleButton44.setBackground(new java.awt.Color(255, 255, 255));
        jToggleButton44.setText(";");
        jPanel1.add(jToggleButton44);
        jToggleButton44.setBounds(568, 341, 39, 41);

        jToggleButton45.setBackground(new java.awt.Color(255, 255, 255));
        jToggleButton45.setText("\\");
            jPanel1.add(jToggleButton45);
            jToggleButton45.setBounds(73, 341, 39, 40);

            jToggleButton46.setBackground(new java.awt.Color(255, 255, 255));
            jToggleButton46.setText("Z");
            jToggleButton46.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jToggleButton46ActionPerformed(evt);
                }
            });
            jPanel1.add(jToggleButton46);
            jToggleButton46.setBounds(118, 341, 39, 40);

            jToggleButton47.setBackground(new java.awt.Color(255, 255, 255));
            jToggleButton47.setText("X");
            jPanel1.add(jToggleButton47);
            jToggleButton47.setBounds(163, 341, 39, 40);

            jToggleButton48.setBackground(new java.awt.Color(255, 255, 255));
            jToggleButton48.setText("C");
            jPanel1.add(jToggleButton48);
            jToggleButton48.setBounds(208, 341, 39, 40);

            jToggleButton49.setBackground(new java.awt.Color(255, 255, 255));
            jToggleButton49.setText("V");
            jToggleButton49.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jToggleButton49ActionPerformed(evt);
                }
            });
            jPanel1.add(jToggleButton49);
            jToggleButton49.setBounds(253, 341, 39, 40);

            jToggleButton50.setBackground(new java.awt.Color(255, 255, 255));
            jToggleButton50.setText("B");
            jToggleButton50.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jToggleButton50ActionPerformed(evt);
                }
            });
            jPanel1.add(jToggleButton50);
            jToggleButton50.setBounds(298, 341, 39, 40);

            jToggleButton51.setBackground(new java.awt.Color(255, 255, 255));
            jToggleButton51.setText("N");
            jToggleButton51.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jToggleButton51ActionPerformed(evt);
                }
            });
            jPanel1.add(jToggleButton51);
            jToggleButton51.setBounds(343, 341, 39, 40);

            jToggleButton52.setBackground(new java.awt.Color(255, 255, 255));
            jToggleButton52.setText("N");
            jToggleButton52.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jToggleButton52ActionPerformed(evt);
                }
            });
            jPanel1.add(jToggleButton52);
            jToggleButton52.setBounds(388, 341, 39, 40);

            jToggleButton53.setBackground(new java.awt.Color(255, 255, 255));
            jToggleButton53.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jToggleButton53ActionPerformed(evt);
                }
            });
            jPanel1.add(jToggleButton53);
            jToggleButton53.setBounds(86, 388, 520, 38);

            lbl_hora.setText("Hora");
            jPanel1.add(lbl_hora);
            lbl_hora.setBounds(20, 20, 80, 14);

            jTextArea1.setColumns(20);
            jTextArea1.setRows(5);
            jTextArea1.addKeyListener(new java.awt.event.KeyAdapter() {
                public void keyPressed(java.awt.event.KeyEvent evt) {
                    jTextArea1KeyPressed(evt);
                }
                public void keyReleased(java.awt.event.KeyEvent evt) {
                    jTextArea1KeyReleased(evt);
                }
            });
            jScrollPane1.setViewportView(jTextArea1);

            jPanel1.add(jScrollPane1);
            jScrollPane1.setBounds(8, 114, 780, 86);

            jToggleButton54.setBackground(new java.awt.Color(255, 255, 255));
            jToggleButton54.setText("BACKSPACE");
            jPanel1.add(jToggleButton54);
            jToggleButton54.setBounds(597, 206, 190, 38);

            jToggleButton55.setBackground(new java.awt.Color(255, 255, 255));
            jToggleButton55.setText("◄");
            jPanel1.add(jToggleButton55);
            jToggleButton55.setBounds(620, 360, 50, 50);

            jToggleButton56.setBackground(new java.awt.Color(255, 255, 255));
            jToggleButton56.setText("▼");
            jPanel1.add(jToggleButton56);
            jToggleButton56.setBounds(680, 360, 50, 50);

            jToggleButton57.setBackground(new java.awt.Color(255, 255, 255));
            jToggleButton57.setText("►");
            jPanel1.add(jToggleButton57);
            jToggleButton57.setBounds(740, 360, 50, 50);

            jToggleButton58.setBackground(new java.awt.Color(255, 255, 255));
            jToggleButton58.setText("▲");
            jPanel1.add(jToggleButton58);
            jToggleButton58.setBounds(680, 300, 50, 50);

            jToggleButton59.setBackground(new java.awt.Color(255, 255, 255));
            jToggleButton59.setText("ENTER");
            jPanel1.add(jToggleButton59);
            jToggleButton59.setBounds(625, 250, 160, 41);

            jLabel3.setText("Digite a frase acima.");
            jPanel1.add(jLabel3);
            jLabel3.setBounds(8, 94, 98, 14);

            jButton1.setBackground(new java.awt.Color(255, 255, 255));
            jButton1.setText("Iniciar Teste");
            jButton1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton1ActionPerformed(evt);
                }
            });
            jPanel1.add(jButton1);
            jButton1.setBounds(450, 10, 140, 23);

            jButton2.setBackground(new java.awt.Color(255, 255, 255));
            jButton2.setText("Finalizar Teste");
            jButton2.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton2ActionPerformed(evt);
                }
            });
            jPanel1.add(jButton2);
            jButton2.setBounds(600, 10, 140, 23);

            jPanel2.setBackground(new java.awt.Color(0, 153, 153));

            lbl_erros.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
            lbl_erros.setForeground(new java.awt.Color(255, 255, 255));

            lbl_erros1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
            lbl_erros1.setForeground(new java.awt.Color(255, 153, 51));

            javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
            jPanel2.setLayout(jPanel2Layout);
            jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lbl_erros)
                        .addComponent(lbl_erros1))
                    .addContainerGap(790, Short.MAX_VALUE))
            );
            jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(lbl_erros)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(lbl_erros1)
                    .addContainerGap(111, Short.MAX_VALUE))
            );

            jPanel1.add(jPanel2);
            jPanel2.setBounds(0, 440, 800, 128);

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 777, Short.MAX_VALUE)
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 586, Short.MAX_VALUE)
            );

            pack();
        }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        finalizarTeste();
        

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jTextArea1.setEnabled(true);
        jToggleButton59.setBackground(null);
        jButton2.setEnabled(true);
        jButton1.setEnabled(false);
        lbl_erros.setText("");
        lbl_erros1.setText("");
        jTextArea1.setText("");
        backspace = 0;

        frases[0] = "Quem traz CD, LP, fax, engov e whisky JB?";
        frases[1] = "Jane quer LP, fax, CD, giz, TV e bom whisky";
        frases[2] = "Bancos fúteis pagavam-lhe queijo e whisky xadrez";
        frases[3] = "TV faz quengo explodir com whisky JB";

        Random gerador = new Random();
        int n = gerador.nextInt(4);
        posicao = n;
        lbl_frase.setText(frases[n]);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextArea1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextArea1KeyReleased
        jToggleButton1.setBackground(null);
        jToggleButton2.setBackground(null);
        jToggleButton3.setBackground(null);
        jToggleButton4.setBackground(null);
        jToggleButton5.setBackground(null);
        jToggleButton6.setBackground(null);
        jToggleButton7.setBackground(null);
        jToggleButton8.setBackground(null);
        jToggleButton9.setBackground(null);
        jToggleButton10.setBackground(null);
        jToggleButton11.setBackground(null);
        jToggleButton12.setBackground(null);
        jToggleButton13.setBackground(null);
        jToggleButton14.setBackground(null);
        jToggleButton15.setBackground(null);
        jToggleButton16.setBackground(null);
        jToggleButton17.setBackground(null);
        jToggleButton18.setBackground(null);
        jToggleButton19.setBackground(null);
        jToggleButton20.setBackground(null);
        jToggleButton21.setBackground(null);
        jToggleButton22.setBackground(null);
        jToggleButton23.setBackground(null);
        jToggleButton24.setBackground(null);
        jToggleButton25.setBackground(null);
        jToggleButton26.setBackground(null);
        jToggleButton27.setBackground(null);
        jToggleButton28.setBackground(null);
        jToggleButton29.setBackground(null);
        jToggleButton30.setBackground(null);
        jToggleButton31.setBackground(null);
        jToggleButton32.setBackground(null);
        jToggleButton33.setBackground(null);
        jToggleButton34.setBackground(null);
        jToggleButton35.setBackground(null);
        jToggleButton36.setBackground(null);
        jToggleButton37.setBackground(null);
        jToggleButton38.setBackground(null);
        jToggleButton39.setBackground(null);
        jToggleButton40.setBackground(null);
        jToggleButton41.setBackground(null);
        jToggleButton42.setBackground(null);
        jToggleButton43.setBackground(null);
        jToggleButton44.setBackground(null);
        jToggleButton45.setBackground(null);
        jToggleButton46.setBackground(null);
        jToggleButton47.setBackground(null);
        jToggleButton48.setBackground(null);
        jToggleButton49.setBackground(null);
        jToggleButton50.setBackground(null);
        jToggleButton51.setBackground(null);
        jToggleButton52.setBackground(null);
        jToggleButton53.setBackground(null);
        jToggleButton54.setBackground(null);
        jToggleButton55.setBackground(null);
        jToggleButton56.setBackground(null);
        jToggleButton57.setBackground(null);
        jToggleButton58.setBackground(null);
        jToggleButton59.setBackground(null);
        jToggleButton1.setBackground(null);
        jToggleButton1.setBackground(null);
        jToggleButton1.setBackground(null);
        jToggleButton1.setBackground(null);
        jToggleButton1.setBackground(null);

    }//GEN-LAST:event_jTextArea1KeyReleased

    private void jTextArea1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextArea1KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_QUOTE) {
            jToggleButton1.setBackground(Color.orange);
        } if (evt.getKeyCode() == KeyEvent.VK_1) {
            jToggleButton2.setBackground(Color.orange);
        } if (evt.getKeyCode() == KeyEvent.VK_2) {
            jToggleButton3.setBackground(Color.orange);
        } if (evt.getKeyCode() == KeyEvent.VK_3) {
            jToggleButton4.setBackground(Color.orange);
        } if (evt.getKeyCode() == KeyEvent.VK_4) {
            jToggleButton5.setBackground(Color.orange);
        } if (evt.getKeyCode() == KeyEvent.VK_5) {
            jToggleButton6.setBackground(Color.orange);
        } if (evt.getKeyCode() == KeyEvent.VK_6) {
            jToggleButton7.setBackground(Color.orange);
        } if (evt.getKeyCode() == KeyEvent.VK_7) {
            jToggleButton8.setBackground(Color.orange);
        } if (evt.getKeyCode() == KeyEvent.VK_8) {
            jToggleButton9.setBackground(Color.orange);
        } if (evt.getKeyCode() == KeyEvent.VK_9) {
            jToggleButton10.setBackground(Color.orange);
        } if (evt.getKeyCode() == KeyEvent.VK_0) {
            jToggleButton11.setBackground(Color.orange);
        } if (evt.getKeyCode() == KeyEvent.VK_MINUS) {
            jToggleButton12.setBackground(Color.orange);
        } if (evt.getKeyCode() == KeyEvent.VK_EQUALS) {
            jToggleButton13.setBackground(Color.orange);
        } if (evt.getKeyCode() == KeyEvent.VK_TAB) {
            jToggleButton14.setBackground(Color.orange);
        } if (evt.getKeyCode() == KeyEvent.VK_Q) {
            jToggleButton15.setBackground(Color.orange);
        } if (evt.getKeyCode() == KeyEvent.VK_W) {
            jToggleButton16.setBackground(Color.orange);
        } if (evt.getKeyCode() == KeyEvent.VK_E) {
            jToggleButton17.setBackground(Color.orange);
        } if (evt.getKeyCode() == KeyEvent.VK_R) {
            jToggleButton18.setBackground(Color.orange);
        } if (evt.getKeyCode() == KeyEvent.VK_T) {
            jToggleButton19.setBackground(Color.orange);
        } if (evt.getKeyCode() == KeyEvent.VK_Y) {
            jToggleButton20.setBackground(Color.orange);
        } if (evt.getKeyCode() == KeyEvent.VK_U) {
            jToggleButton21.setBackground(Color.orange);
        } if (evt.getKeyCode() == KeyEvent.VK_I) {
            jToggleButton22.setBackground(Color.orange);
        } if (evt.getKeyCode() == KeyEvent.VK_O) {
            jToggleButton23.setBackground(Color.orange);
        } if (evt.getKeyCode() == KeyEvent.VK_P) {
            jToggleButton24.setBackground(Color.orange);
        } if (evt.getKeyCode() == KeyEvent.VK_0) {
            jToggleButton25.setBackground(Color.orange);
        } if (evt.getKeyCode() == KeyEvent.VK_OPEN_BRACKET) {
            jToggleButton26.setBackground(Color.orange);
        } if (evt.getKeyCode() == KeyEvent.VK_0) {
            jToggleButton27.setBackground(Color.orange);
        } if (evt.getKeyCode() == KeyEvent.VK_A) {
            jToggleButton28.setBackground(Color.orange);
        } if (evt.getKeyCode() == KeyEvent.VK_S) {
            jToggleButton29.setBackground(Color.orange);
        } if (evt.getKeyCode() == KeyEvent.VK_D) {
            jToggleButton30.setBackground(Color.orange);
        } if (evt.getKeyCode() == KeyEvent.VK_F) {
            jToggleButton31.setBackground(Color.orange);
        } if (evt.getKeyCode() == KeyEvent.VK_G) {
            jToggleButton32.setBackground(Color.orange);
        } if (evt.getKeyCode() == KeyEvent.VK_H) {
            jToggleButton33.setBackground(Color.orange);
        } if (evt.getKeyCode() == KeyEvent.VK_J) {
            jToggleButton34.setBackground(Color.orange);
        } if (evt.getKeyCode() == KeyEvent.VK_K) {
            jToggleButton35.setBackground(Color.orange);
        } if (evt.getKeyCode() == KeyEvent.VK_L) {
            jToggleButton36.setBackground(Color.orange);
        } if (evt.getKeyCode() == KeyEvent.VK_0) {
            jToggleButton37.setBackground(Color.orange);
        } if (evt.getKeyCode() == KeyEvent.VK_DEAD_TILDE) {
            jToggleButton38.setBackground(Color.orange);
        } if (evt.getKeyCode() == KeyEvent.VK_CLOSE_BRACKET) {
            jToggleButton39.setBackground(Color.orange);
        } if (evt.getKeyCode() == KeyEvent.VK_SHIFT) {
            jToggleButton40.setBackground(Color.orange);
        } if (evt.getKeyCode() == KeyEvent.VK_SLASH) {
            jToggleButton41.setBackground(Color.orange);
        } if (evt.getKeyCode() == KeyEvent.VK_COMMA) {
            jToggleButton42.setBackground(Color.orange);
        } if (evt.getKeyCode() == KeyEvent.VK_PERIOD) {
            jToggleButton43.setBackground(Color.orange);
        } if (evt.getKeyCode() == KeyEvent.VK_0) {
            jToggleButton44.setBackground(Color.orange);
        } if (evt.getKeyCode() == KeyEvent.VK_0) {
            jToggleButton45.setBackground(Color.orange);
        } if (evt.getKeyCode() == KeyEvent.VK_Z) {
            jToggleButton46.setBackground(Color.orange);
        } if (evt.getKeyCode() == KeyEvent.VK_X) {
            jToggleButton47.setBackground(Color.orange);
        } if (evt.getKeyCode() == KeyEvent.VK_C) {
            jToggleButton48.setBackground(Color.orange);
        } if (evt.getKeyCode() == KeyEvent.VK_V) {
            jToggleButton49.setBackground(Color.orange);
        } if (evt.getKeyCode() == KeyEvent.VK_B) {
            jToggleButton50.setBackground(Color.orange);
        } if (evt.getKeyCode() == KeyEvent.VK_N) {
            jToggleButton51.setBackground(Color.orange);
        } if (evt.getKeyCode() == KeyEvent.VK_M) {
            jToggleButton52.setBackground(Color.orange);
        } if (evt.getKeyCode() == KeyEvent.VK_SPACE) {
            jToggleButton53.setBackground(Color.orange);
        } if (evt.getKeyCode() == KeyEvent.VK_BACK_SPACE) {
            backspace++;
            jToggleButton54.setBackground(Color.orange);
        } if (evt.getKeyCode() == KeyEvent.VK_LEFT) {
            jToggleButton55.setBackground(Color.orange);
        } if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
            jToggleButton56.setBackground(Color.orange);
        } if (evt.getKeyCode() == KeyEvent.VK_RIGHT) {
            jToggleButton57.setBackground(Color.orange);
        } if (evt.getKeyCode() == KeyEvent.VK_UP) {
            jToggleButton58.setBackground(Color.orange);
        } if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jToggleButton59.setBackground(Color.orange);
            finalizarTeste();
        }
    }//GEN-LAST:event_jTextArea1KeyPressed

    private void jToggleButton53ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton53ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton53ActionPerformed

    private void jToggleButton52ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton52ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton52ActionPerformed

    private void jToggleButton51ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton51ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton51ActionPerformed

    private void jToggleButton50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton50ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton50ActionPerformed

    private void jToggleButton49ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton49ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton49ActionPerformed

    private void jToggleButton46ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton46ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton46ActionPerformed

    private void jToggleButton33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton33ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton33ActionPerformed

    private void jToggleButton30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton30ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton30ActionPerformed

    private void jToggleButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton23ActionPerformed

    private void jToggleButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton17ActionPerformed

    private void jToggleButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton14ActionPerformed

    private void jToggleButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton13ActionPerformed

    private void jToggleButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton10ActionPerformed

    private void jToggleButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton6ActionPerformed

    private void jToggleButton2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jToggleButton2KeyReleased

    }//GEN-LAST:event_jToggleButton2KeyReleased

    private void jToggleButton2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jToggleButton2KeyPressed

 
    }//GEN-LAST:event_jToggleButton2KeyPressed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jToggleButton32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton32ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton32ActionPerformed
    public void finalizarTeste(){
        //habilitando e desabilitando objetos
       
        jButton2.setEnabled(false);
        jTextArea1.setEnabled(false);
        jButton1.setEnabled(true);
        lbl_frase.setText("");
        int erros = 0;
        String frase = jTextArea1.getText();
        int total = 0;
        double per;
        
       if(frase.isEmpty()){ 
       total =  frases[posicao].length();
       
       per = ((total*100)/frases[posicao].length());
       lbl_erros.setText("Erros " +total);
       lbl_erros1.setText("Percentual: " +per+"%");
       }
        if (frase.length()!=frases[posicao].length()){
          for (int i=0; i < frase.length(); i++){
              if(frase.charAt(i)!=frases[posicao].charAt(i)){
                erros++;
              }
          }
       total = backspace + erros + (frases[posicao].length()-frase.length());
        
        per = ((total*100)/frases[posicao].length());
        lbl_erros.setText("Erros " +total);
        lbl_erros1.setText("Percentual: " +per+"%");
        
        }else if(frase.length()==frases[posicao].length()) {
        for (int i=0; i < frases[posicao].length(); i++){
              if(frase.charAt(i)!=frases[posicao].charAt(i)){
                erros++;
         }
          }        
        
        total = erros + backspace; 
                
        per = ((total*100)/frases[posicao].length());
        lbl_erros.setText("Erros " +total);
        lbl_erros1.setText("Percentual: " +per+"%");
           
        }  
        
           
        
    } 

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows Classic".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton10;
    private javax.swing.JToggleButton jToggleButton11;
    private javax.swing.JToggleButton jToggleButton12;
    private javax.swing.JToggleButton jToggleButton13;
    private javax.swing.JToggleButton jToggleButton14;
    private javax.swing.JToggleButton jToggleButton15;
    private javax.swing.JToggleButton jToggleButton16;
    private javax.swing.JToggleButton jToggleButton17;
    private javax.swing.JToggleButton jToggleButton18;
    private javax.swing.JToggleButton jToggleButton19;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton20;
    private javax.swing.JToggleButton jToggleButton21;
    private javax.swing.JToggleButton jToggleButton22;
    private javax.swing.JToggleButton jToggleButton23;
    private javax.swing.JToggleButton jToggleButton24;
    private javax.swing.JToggleButton jToggleButton25;
    private javax.swing.JToggleButton jToggleButton26;
    private javax.swing.JToggleButton jToggleButton27;
    private javax.swing.JToggleButton jToggleButton28;
    private javax.swing.JToggleButton jToggleButton29;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton jToggleButton30;
    private javax.swing.JToggleButton jToggleButton31;
    private javax.swing.JToggleButton jToggleButton32;
    private javax.swing.JToggleButton jToggleButton33;
    private javax.swing.JToggleButton jToggleButton34;
    private javax.swing.JToggleButton jToggleButton35;
    private javax.swing.JToggleButton jToggleButton36;
    private javax.swing.JToggleButton jToggleButton37;
    private javax.swing.JToggleButton jToggleButton38;
    private javax.swing.JToggleButton jToggleButton39;
    private javax.swing.JToggleButton jToggleButton4;
    private javax.swing.JToggleButton jToggleButton40;
    private javax.swing.JToggleButton jToggleButton41;
    private javax.swing.JToggleButton jToggleButton42;
    private javax.swing.JToggleButton jToggleButton43;
    private javax.swing.JToggleButton jToggleButton44;
    private javax.swing.JToggleButton jToggleButton45;
    private javax.swing.JToggleButton jToggleButton46;
    private javax.swing.JToggleButton jToggleButton47;
    private javax.swing.JToggleButton jToggleButton48;
    private javax.swing.JToggleButton jToggleButton49;
    private javax.swing.JToggleButton jToggleButton5;
    private javax.swing.JToggleButton jToggleButton50;
    private javax.swing.JToggleButton jToggleButton51;
    private javax.swing.JToggleButton jToggleButton52;
    private javax.swing.JToggleButton jToggleButton53;
    private javax.swing.JToggleButton jToggleButton54;
    private javax.swing.JToggleButton jToggleButton55;
    private javax.swing.JToggleButton jToggleButton56;
    private javax.swing.JToggleButton jToggleButton57;
    private javax.swing.JToggleButton jToggleButton58;
    private javax.swing.JToggleButton jToggleButton59;
    private javax.swing.JToggleButton jToggleButton6;
    private javax.swing.JToggleButton jToggleButton7;
    private javax.swing.JToggleButton jToggleButton8;
    private javax.swing.JToggleButton jToggleButton9;
    private javax.swing.JLabel lbl_erros;
    private javax.swing.JLabel lbl_erros1;
    private javax.swing.JLabel lbl_frase;
    private javax.swing.JLabel lbl_hora;
    // End of variables declaration//GEN-END:variables
}
